In [2]:
import torch

In [5]:
x= torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
x.shape

torch.Size([12])

In [7]:
x.numel()

12

In [8]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
#第0维合并就是在行上堆砌，第一维合并就是在行上续
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [11]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [12]:
x.sum()

tensor(66.)

In [13]:
# broadcast meachnaism 如果形状不同，会自动补全成最大的维数
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [14]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [15]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [16]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B) 

(numpy.ndarray, torch.Tensor)

In [1]:
import os

In [15]:
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')

with open (data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,10600\n')
    f.write('4,NA,17800\n')
    f.write('NA,NA,14000\n')
    

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv(data_file)
data

NumRooms Alley  Prince
0       NaN  Pave  127500
1       2.0   NaN   10600
2       4.0   NaN   17800
3       NaN   NaN   14000

In [19]:
#只将第0列用平均值填充
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs['NumRooms']= inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
inputs

NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [23]:
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True

In [27]:
import torch
x,y = torch.tensor(inputs.to_numpy(dtype=float)),torch.tensor(outputs.to_numpy(dtype=float))
x,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500.,  10600.,  17800.,  14000.], dtype=torch.float64))

In [33]:
import pandas as pd

def remove_most_missing_column(df):
    # 计算每一列的缺失值数量
    missing_counts = df.isnull().sum()
    print(missing_counts)
    # 找到缺失值最多的列
    column_to_drop = missing_counts.idxmax()
    
    # 删除该列
    df_dropped = df.drop(columns=[column_to_drop])
    
    return df_dropped

# 示例用法
data = {
    'A': [1, 2, None, 4],
    'B': [None, None, 3, 4],
    'C': [1, 2, 3, None]
}

df = pd.DataFrame(data)
print("原始数据表:")
print(df)

df_cleaned = remove_most_missing_column(df)
print("\n删除缺失最多的列后的数据表:")
print(df_cleaned)

原始数据表:
     A    B    C
0  1.0  NaN  1.0
1  2.0  NaN  2.0
2  NaN  3.0  3.0
3  4.0  4.0  NaN
A    1
B    2
C    1
dtype: int64

删除缺失最多的列后的数据表:
     A    C
0  1.0  1.0
1  2.0  2.0
2  NaN  3.0
3  4.0  NaN


In [ ]:
"""
线性代数
我们正在训练一个模型来预测贷款违约风险，可能会将每个申请人与一个向量相关联， 其分量与其收入、工作年限、过往违约次数和其他因素相对应。
如果我们正在研究医院患者可能面临的心脏病发作风险，可能会用一个向量来表示每个患者， 其分量为最近的生命体征、胆固醇水平、每天运动时间等
"""

In [34]:
x = torch.tensor([3.0])
y = torch.tensor([4.0])
x+y,x*y,x/y,x**y

(tensor([7.]), tensor([12.]), tensor([0.7500]), tensor([81.]))

In [35]:
A = torch.arange(20).reshape((5,4))
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [36]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [38]:
A = torch.arange(20,dtype=float).reshape((5,4))
B = A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]], dtype=torch.float64))

In [39]:
#multiple by elements is called hadamard product  点乘
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]], dtype=torch.float64)

In [41]:
a = 2
A = torch.arange(12).reshape((3,4))
A,a+A,(a*A).shape

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]]),
 torch.Size([3, 4]))

In [42]:
A.sum()

tensor(66)

In [46]:
B = A.sum(axis=0)
C = A.sum(axis=1)
B,C

(tensor([12, 15, 18, 21]), tensor([ 6, 22, 38]))

In [47]:
B.shape,C.shape

(torch.Size([4]), torch.Size([3]))

In [49]:
a = torch.ones((2,5,4))
a

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [52]:
a.sum(axis=[1,2],keepdim=True).shape

torch.Size([2, 1, 1])

In [76]:
#automatic derivation
x= torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [77]:
x.requires_grad_(True)
x.grad

In [78]:
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [79]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [80]:
x.grad == 4 * x

tensor([True, True, True, True])

In [83]:
#在默认情况下，Pytorch 会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])